name: my_flutter_app
description: A well-structured Flutter project with routing.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  cupertino_icons: ^1.0.2
  go_router: ^14.0.0
  intl: ^0.20.2
  mobile_scanner: ^5.2.3
  http: ^1.1.0
  flutter_secure_storage: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  google_maps_flutter: ^2.5.0

flutter:
  uses-material-design: true

  assets:
      - assets/bottombar/catalog.svg
      - assets/bottombar/orders.svg
      - assets/bottombar/scaner.svg
      - assets/bottombar/smart-home.svg
      - assets/bottombar/user.svg
      - assets/restaurant/
      - assets/restaurant/maxway/
      - assets/restaurant/evos/
      - assets/meals/
      - assets/meals/maxway/
      - assets/meals/evos/
      - assets/category/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic